# .github/workflows/use-export-kicad.yml
name: Use Export KiCad Images Workflow

on:
  push:
    branches:
      - main
    paths:
      - '**/*.kicad_sch'
      - '**/*.kicad_pcb'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  call-workflow:
    uses: sonicavionics/shared-workflows/.github/workflows/export-kicad-images.yml@main
